src/Reopt/Relinker.hs

@joehendrix  The code here failed to compile due to warnings on `-4 :: Word32` and `-Werror`.  I'm not clear on the intent as it seems odd - could you confirm that whatever is going on was actually intended prior to merge?

Word literal overflow falls afoul of GHC warnings

---

.github/workflows/ci.yaml

`add-path` and `set-env` have been deprecated as of 10/1/2020 and will be removed, this patch replaces them with environment files to keep the existing workflows running.

Replace deprecated GitHub Actions functions

---

reopt-explore/Main_explore.hs
reopt.cabal
reopt/Main_reopt.hs
src/Reopt.hs
tests/ReoptTests.hs

Adds the following recovery statistics flags to `reopt`:
```
--print-stats               Print discovery/recovery statistics.
--export-stats=PATH         Path at which to write discovery/recovery
statistics.
```
E.g., `reopt --print-stats fib_test.1234` will run reopt through discovery/recovery and then emit a summary (i.e., starting with "reopt discovered ...") after completing:
```
$ reopt --print-stats fib_test.1234
...
reopt discovered 1086 functions:
recovery succeeded: 287 (26.43%)
recovery failed: 799 (73.57%)
skipped PLT stub: 0 (0.00%)
800 errors occured.
```
whereas using the `--export-stats=PATH` flag will output the recovery statistics info a CSV file named `PATH` with a header in the first line and data entries on the remaining lines, e.g.:
```
binary,fn name,address,recovery …
```

feat: reopt stats reporting/exporting

---

reopt/Main_reopt.hs

I think it's supposed to be functions here.

copy-paste mistake in reopt help labels

---

src/Reopt.hs
src/Reopt/CFG/Recovery.hs
src/Reopt/Events.hs
src/Reopt/Events/Export.hs

This adds block size to the `CFGError` datatype so that IDE frontends can decide to highlight the whole block.
I'm a little spooked by the two unlabeled `Int` fields, if this datatype becomes any more populated it probably ought to have named fields.

reopt: log block size

---

src/Reopt/CFG/LLVM.hs
src/Reopt/CFG/LLVM/X86.hs

Adds support for translating Macaw's [MemCmp](https://github.com/GaloisInc/macaw/blob/e4b198ab2dd882e34690ed33056d5231b2d776bf/x86/src/Data/Macaw/X86/ArchTypes.hs#L373) x86 primitive to LLVM, which is used to support `repx cmpsx` occurrences in machine code which compare blocks of memory.
Makes small but non-zero improvements to recovery statistics:
```
diff -U1 pre_pr.txt post_pr.txt 
--- pre_pr.txt	2021-08-09 12:18:18.000000000 -0700
+++ post_pr.txt	2021-08-12 10:59:51.000000000 -0700
@@ -28,6 +28,7 @@
Recovery:
-  Succeeded: 21,868 (72%)
-  Failed: 8,353 (28%)
-    Unsupported function value: 2,396 (8%)
-    Unimplemented LLVM backend feature: 4,881 (16%)
+  Succeeded: 21,952 (73%)
+  Failed: 8,269 (27%)
+    Unsupported function value: 2,425 (8%)
+    Unimplemented feature: 6 (0%)
+ …
```

feat: reopt memcmp support for LLVM trans (i.e., 'repx cmpsx' in x86)

---

examples/add/Makefile
examples/fib/Makefile
examples/nweb/Makefile

With these changes, if I visit the Gitpod link which includes them (i.e., https://gitpod.io/#https://github.com/GaloisInc/reopt/tree/pnwamk/try-reopt in this case) I am able to `cd` into each subdirectory in the `examples` directory and run `make`, which builds the executable, runs `reopt`, and then runs `reopt-vcg`.
The only failures are the few known remaining issues for our `nweb` example's verification condition checking, i.e.:
```
Generating verification conditions for LLVM module...
........................................................................................................................
FAIL
reopt_frame_dummy_0_0x4012b0.block_0_4012b0.0 @ 0x4012b4: return address is next instruction
Verification failed: the SMT query returned `sat`
To see the output, run `reopt-vcg …
```

fix: update example reopt flags

---

reopt.cabal
src/Reopt/TypeInference/Constraints.hs
tests/Main.hs
tests/TyConstraintTests.hs

Includes an initial implementation of the core of the type constraint system described in "TIE: Principled Reverse Engineering of Types in Binary Programs" and a few simple tests.
Notable omissions at present are as follows:
+ no memory/record representation currently (presumably this isn't _hard_ to add per se, but it appears to involve lots of subtleties the paper hand waves about presumably for LaTeX clarity)
+ we do not _merge_ info from disjunctions yet (see §6.3.4 of TIE paper), we only see if certain disjuncts are absurd and attempt to reduce the disjunction into simpler constraint

initial implementation of types and constraints

---

reopt/Main_reopt.hs
src/Reopt/TypeInference/ConstraintGen.hs

We can now run the pipeline of constraint generation all the way through
constraint solving and display the results of the solving process.
Results are now displaying the generated constraints (which are informative but
in terms of fresh type variables so hard to understand), and the inferred types
for all user-facing variables.
This also solves a bug where we were conflating `FnAssignId`s across
`Function`s, and reengineers the constraint generation monad to be
parameterized by an increasingly-populated context as we go down modules,
functions, and function blocks.

connect constraint generation and constraint solving

---

src/Reopt/TypeInference/Constraints.hs
tests/TyConstraintTests.hs

Adds a record type (`RecTy`) and types essentially for describing indexing into records (`ReadAtTy`) and updating records (`UpdateAtTy`). The intent is that `ReadAtTy` and `UpdateAtTy` _only_ appear in types when the underlying type being indexed/updated is unknown, and once the underlying type is known and has an appropriate structure the type is reduced (see smart constructors `readAtTy` and `updateAtTy`). These type constructors correspond to some of the undocumented type operators that appear in the TIE paper (e.g., see Figure 7's entries for `load` and `store`).
Records are treated elementary presently (e.g., we treat them as maps from offsets to types, but ignore possible overlap etc); this could obviously be enhanced if desired. (It's not clear in my mind how much effort is …

structural constraint types

---

reopt.cabal
src/Reopt/TypeInference/ConstraintGen.hs
src/Reopt/TypeInference/Constraints.hs
src/Reopt/TypeInference/Pretty.hs
tests/TyConstraintTests.hs

This adds some functionality and basic tests so constraints regarding record types can be sensibly combined.
E.g., `x <: {0 : τ1}` and `x <: {64 : τ2}` can now essentially be unified into the constraint `x <: {0 : τ1, 64 : τ2}`.

improved record constraint reasoning

---

src/Reopt/TypeInference/ConstraintGen.hs
src/Reopt/TypeInference/Constraints.hs
tests/TyConstraintTests.hs

Reintroduces sizes in `NumTy`.
These will be needed for the next pull request improving LLVM generation.

reintroduce size for NumTy

---

src/Reopt/TypeInference/ConstraintGen.hs

We were unfortunately creating two separate type variables for phi nodes'
`FnAssignId`s: one where the phi node was emitted, and one the first time the
phi variable was referenced in code.
We now make sure to check for an existing type variable for any `FnAssignId`
before deciding to create a fresh one.

don't create two type variables for phi nodes

---

src/Reopt/CFG/LLVM.hs

When emitting `getelementptr`, we know the pointee type, and it does not
correspond to the type obtained in recovery (which will always be `i64`).
Therefore we need to ignore that type and put the actual, inferred pointee
type.

override pointer type when emitting `getelementptr`

---

src/Reopt/TypeInference/Solver/Monad.hs
src/Reopt/TypeInference/Solver/Types.hs
src/Reopt/TypeInference/Solver/UnionFindMap.hs

Before:
```
EqCs []
EqRowCs []
PtrAddCs []
Type Var Map [ Equivalences []
Definitions [ α0 (f.arg0) → ptr(α6)
, α1 (f.arg1) → ptr(α11)
, α2 (f.arg2) → ptr(α16)
, α3 (f.arg3) → ptr(α5)
, α5 → {0 : α4 (f.r0), 8 : α9 (f.r3), 16 : α14 (f.r6)|ρ11}
, α6 → {0 : α4 (f.r0)|ρ1}
, α7 (f.r1) → i64
, α8 (f.r2) → ptr(α10)
, α10 → {-8 : α4 (f.r0), 0 : α9 (f.r3), 8 : α14 (f.r6)|shift 8 ρ11}
, α11 → {0 : α9 (f.r3)|ρ3}
, α12 (f.r4) → i64
, α13 (f.r5) → ptr(α15)
, α15 → {-16 : α4 (f.r0), -8 : α9 (f.r3), 0 : α14 (f.r6)|shift 16 ρ11}
, α16 → {0 : α14 (f.r6)|ρ5} ] ]
```
After:
```
EqCs []
EqRowCs []
PtrAddCs []
Equivalences []
Definitions [ α0 (f.arg0) → ptr(α6)
, α1 (f.arg1) → ptr(α11)
, α2 (f.arg2) → ptr(α16)
, α3 (f.arg3) → ptr(α5)
, α5 → {0 : α4 (f.r0), 8 : α9 (f.r3), 16 : α14 (f.r6)| ρ11}
, α6 → {0 : α4 …
```

improve pretty-printing

---

scripts/unpack_benchmarks.sh

The current script does not work on my machine because it assumes that any
machine running Darwin will also have bsdtar.  I am running Darwin, but have
also installed the superior GNU tar, so the assumption does not hold.
Instead, I made it read the `--version` output to see if we identify either GNU
or BSD version of tar.

detect the actual tar version present on the system

---

.github/workflows/ci.yaml
annotations/src/Reopt/VCG/Annotations.hs
annotations/src/Reopt/VCG/SMTParser.hs
containers/dev-with-builds/Dockerfile
containers/dev/Dockerfile
reopt-explore/Residual.hs
reopt-explore/Residual/Recognizers.hs
reopt-relink/Main_relink.hs
reopt.cabal
reopt/Main_reopt.hs
src/Reopt/Analysis/Domains/DiffEquations.hs
src/Reopt/CFG/LLVM.hs
src/Reopt/CFG/Recovery.hs
src/Reopt/CFG/StackDepth.hs
src/Reopt/Occam.hs
src/Reopt/Server.hs

Lots of changes:
- Removed dependency on the bitrotting base-encoding, favoring base64 instead.
- Bumped to aeson 2.
- Put an upper bound on hashable since our dependencies don't work with 1.4.
- Removed many causes of warnings.

make GHC 9.2.6 compatible

---

src/Reopt/TypeInference/Solver/Monad.hs

The output of pretty-printing the provenance of Conditionals is often verbose to the point of overwhelming everything else, so I haven't enabled this by default. Nevertheless, I've made it simple to uncomment one line of code to opt into this if desired.

--trace-constraint-origins: Make it possible to print Conditionals

---

cabal.project

cabal now fails to build reopt-explore because it uses deprecated ansi-wl-pprint.
I have made changes upstream to flexdis86 so that it uses prettyprinter instead: https://github.com/GaloisInc/flexdis86/pull/53
But in the meantime, this makes cabal be less stringent.

temp fix for ansi-wl-pprint deprecation

---

reopt-explore/Residual.hs
src/Reopt.hs
src/Reopt/Events.hs

I'm constantly frustrated by the output of Reopt. This makes it a bit more verbose, not great, but at least gives a vague idea of what is going okay, and what is going wrong.
BEFORE:
```
Initialization
Complete.
Searching for dynamic dependency libc.so.6's debug info...
No debug info for libc.so.6 found.
Header Processing
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Block 0x40547a: Unclassified control flow transfer.
Incomplete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete.
Complete. …
```

make reopt output more readable for humans

---

.github/workflows/ci.yaml
containers/dev/Dockerfile

For a while the CI was being annoying and taking anything from 20 minutes to 1h30 for changes that ought to take 5 minutes.
This updates CI to use recent tooling, and fixes the (still manual) caching of the cabal store.
I will try to replace this with vetted Haskell CI actions next, but at least this fixes the current annoyance.

update CI and solve caching issues

---

.github/workflows/ci.yaml

Can't use the Haskell setup action because it gives back the wrong location for the cabal store when it has not installed it itself.
But the rest seems to work well.

using Haskell actions

---

reopt/Main_reopt.hs
src/Reopt.hs
src/Reopt/ELFArchInfo.hs
src/Reopt/Events.hs
src/Reopt/Events/Export.hs

For debugging block terminator classifying failures, it helps to have much more information.  This switches from a `Text`-based error message to a `Doc`-based error message to support easier rendering of complex error descriptions, including a listing of the instructions leading to classiying failures for block terminator statements.

use Doc for discovery error messages

---

reopt/Main_reopt.hs
src/Reopt.hs

With a bit of extra refactoring, all uses of Reopt's discovery can use the same helper function, rather than re-doing very similar work in multiple places.
Also renamed the confusing `checkSymbolUnused` into something a little more explicit.

use `reoptPrepareForRecovery` where possible

---

src/Reopt/TypeInference/Solver/Constraints.hs

When debugging larger datatypes that contain deep instances of `EqC`s, it's much more convenient to be able to change the `Pretty`.

make `ppEqCWithProv` usable by the `Pretty` instance

---

src/Reopt/TypeInference/DebugTypes.hs

Before:
__libc_start_main ↦ i32 (main : void*, argc : i32, argv : void*, init : void*, fini : void*, rtld_fini : void*, stack_end : void*)
After:
__libc_start_main ↦ i32 (main : i32 (i32,i8**,i8**), argc : i32, argv : i8**, init : i32 (i32,i8**,i8**), fini : void (), rtld_fini : void (), stack_end : void*)

add support for function pointer types from DWARF

---

src/Reopt.hs
src/Reopt/ArgResolver.hs
src/Reopt/CFG/Recovery.hs
src/Reopt/TypeInference/DebugTypes.hs
src/Reopt/TypeInference/FunTypeMaps.hs
src/Reopt/TypeInference/HeaderTypes.hs

Given a function with known symbols (e.g. a function from `libc`), Reopt now checks if any of its arguments are expected to be function pointers. If they are, Reopt instructs Macaw to add them to the discovery frontier.
This significantly improves Reopt's performance on stripped binaries, since Reopt wasn't previously able to discover the main function and conduct any meaningful analysis on the binary. Since `main` is a function pointer argument to `libc_start_main`, Reopt now adds it to the frontier.

Add known function pointers to discovery frontier

---

src/Reopt/CFG/LLVM.hs

The old code was doing pattern-matching on a shape for some type, and binding the insides of the constructor to a variable name, but then using that variable as if it still had the constructor around.

fix pattern-matching binding bug
